// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Film struct {
	Title       string  `json:"title"`
	EpisodeID   int     `json:"episodeId"`
	Director    *string `json:"director,omitempty"`
	Producer    *string `json:"producer,omitempty"`
	ReleaseDate *string `json:"releaseDate,omitempty"`
}

type Mutation struct {
}

type People struct {
	Name      string     `json:"name"`
	Height    *string    `json:"height,omitempty"`
	Mass      *string    `json:"mass,omitempty"`
	HairColor *string    `json:"hairColor,omitempty"`
	SkinColor *string    `json:"skinColor,omitempty"`
	EyeColor  *string    `json:"eyeColor,omitempty"`
	BirthYear *string    `json:"birthYear,omitempty"`
	Gender    *string    `json:"gender,omitempty"`
	Films     []*Film    `json:"films,omitempty"`
	Vehicles  []*Vehicle `json:"vehicles,omitempty"`
	Created   *string    `json:"created,omitempty"`
	Edited    *string    `json:"edited,omitempty"`
	URL       string     `json:"url"`
}

type Query struct {
}

type SearchResult struct {
	Key  string   `json:"key"`
	Urls []string `json:"urls"`
}

type Vehicle struct {
	Name  string `json:"name"`
	Model string `json:"model"`
}

type SaveResultResponse struct {
	Message string `json:"message"`
}
